appVersion: 9.4.1
deprecated: true
description: GitLab Enterprise Edition
home: https://about.gitlab.com
icon: file://../icon.png
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
name: gitlab-ee
sources:
- https://hub.docker.com/r/gitlab/gitlab-ee/
- https://docs.gitlab.com/omnibus/
version: 0.2.2
