apiVersion: v1
appVersion: 5.0.0
deprecated: true
description: DEPRECATED Searchlight by AppsCode - Alerts for Kubernetes
home: https://github.com/appscode/searchlight
icon: file://../icon.png
name: searchlight
sources:
- https://github.com/appscode/searchlight
version: 0.3.3
