apiVersion: v1
appVersion: '3'
deprecated: true
description: DEPRECATED Agent for Buildkite
home: https://buildkite.com
icon: file://../icon.png
keywords:
- kubernetes deployment
- helm release
- continuous deployment
- continuous integration
name: buildkite
sources:
- https://github.com/buildkite/agent
version: 0.2.4
