apiVersion: v1
appVersion: '6'
description: A Helm chart for ELK
home: https://www.elastic.co/products
icon: file://../icon.svg
maintainers:
- email: pete.brown@powerhrg.com
  name: rendhalver
- email: jrodgers@powerhrg.com
  name: jar361
- email: christian.roggia@gmail.com
  name: christian-roggia
name: elastic-stack
version: 1.8.0
