apiVersion: v1
appVersion: 10.2.1
description: A file sharing server that puts the control and security of your own
  data back into your hands.
engine: gotpl
home: https://owncloud.org/
icon: file://../icon.png
keywords:
- owncloud
- storage
- http
- web
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: owncloud
sources:
- https://github.com/bitnami/bitnami-docker-owncloud
version: 6.2.3
