apiVersion: v1
appVersion: 2019.36.0
description: Collection of open source web applications that help software companies
  build better software.
engine: gotpl
home: https://www.phacility.com/phabricator/
icon: file://../icon.png
keywords:
- phabricator
- http
- https
- web
- application
- collaboration
- project management
- bug tracking
- code review
- wiki
- git
- mercurial
- subversion
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: phabricator
sources:
- https://github.com/bitnami/bitnami-docker-phabricator
version: 7.0.6
