apiVersion: v1
appVersion: 3.2.7
description: Community forum that supports the notion of users and groups, file attachments,
  full-text search, notifications and more.
engine: gotpl
home: https://www.phpbb.com/
icon: file://../icon.png
keywords:
- phpbb
- forum
- http
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: phpbb
sources:
- https://github.com/bitnami/bitnami-docker-phpbb
version: 6.2.1
