apiVersion: v1
appVersion: '1.0'
description: Helm chart for deploying Sematext Agent to Kubernetes
home: https://sematext.com/cloud
icon: file://../icon.png
keywords:
- sematext
- observability
- monitoring
- logging
- containers
- ebpf
maintainers:
- email: alen.komljen@sematext.com
  name: komljen
name: sematext-agent
version: 1.0.9
