apiVersion: v1
appVersion: 1.2.0
description: Containerized Storage for Containers
home: http://www.openebs.io/
icon: file://../icon.png
keywords:
- cloud-native-storage
- block-storage
- iSCSI
- storage
maintainers:
- email: kiran.mova@openebs.io
  name: kmova
- email: prateek.pandey@openebs.io
  name: prateekpandey14
name: openebs
sources:
- https://github.com/openebs/openebs
version: 1.2.0
