apiVersion: v1
appVersion: 1.2.0
description: A Helm chart for kured
home: https://github.com/weaveworks/kured
icon: file://../icon.png
maintainers:
- email: plummer574@gmail.com
  name: plumdog
- email: pslattery@mi9retail.com
  name: patrickmslatteryvt
name: kured
sources:
- https://github.com/weaveworks/kured
version: 1.3.1
