apiVersion: v1
appVersion: 1.1.0
deprecated: true
description: DEPRECATED A Helm chart for JFrog Distribution
home: https://jfrog.com/platform/
icon: file://../icon.png
keywords:
- distribution
- jfrog
name: distribution
sources:
- https://bintray.com/jfrog/product/distribution/view
- https://github.com/JFrogDev
version: 0.4.2
