appVersion: 1.10.0
description: Airflow is a platform to programmatically author, schedule and monitor
  workflows
home: https://airflow.apache.org/
icon: file://../icon.png
keywords:
- workflow
- dag
maintainers:
- email: gaetan@xeberon.net
  name: gsemet
name: airflow
sources:
- https://airflow.apache.org/
version: 0.9.1
