apiVersion: v1
appVersion: 5.0.5
description: Highly available Kubernetes implementation of Redis
engine: gotpl
home: http://redis.io/
icon: file://../icon.png
keywords:
- redis
- keyvalue
- database
maintainers:
- email: salimsalaues@gmail.com
  name: ssalaues
- email: aaron.layfield@gmail.com
  name: dandydeveloper
name: redis-ha
sources:
- https://redis.io/download
- https://github.com/scality/Zenko/tree/development/1.0/kubernetes/zenko/charts/redis-ha
- https://github.com/oliver006/redis_exporter
version: 3.7.7
