apiVersion: v1
appVersion: 19.1.1
description: CockroachDB is a scalable, survivable, strongly-consistent SQL database.
home: https://www.cockroachlabs.com
icon: file://../icon.png
maintainers:
- email: alexdwanerobinson@gmail.com
  name: a-robinson
- email: Joel.A.Kenny@gmail.com
  name: DuskEagle
- email: joshimhoff13@gmail.com
  name: joshimhoff
- email: keith.mcclellan@gmail.com
  name: keith-mcclellan
name: cockroachdb
sources:
- https://github.com/cockroachdb/cockroach
version: 2.1.9
