apiVersion: v1
appVersion: 1.1.0
description: A Helm chart for velero
home: https://github.com/heptio/velero
icon: file://../icon.png
maintainers:
- email: d-caruso@hotmail.it
  name: domcar
- email: hfernandez@mesosphere.com
  name: hectorj2f
- email: brubakern@vmware.com
  name: nrb
- email: aadnan@vmware.com
  name: prydonius
name: velero
sources:
- https://github.com/heptio/velero
tillerVersion: '>=2.10.0'
version: 2.1.6
