apiVersion: v1
appVersion: '0.2'
description: A Helm chart for eventruter (https://github.com/heptiolabs/eventrouter)
home: https://github.com/heptiolabs/eventrouter
icon: file://../icon.png
keywords:
- eventrouter
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
name: eventrouter
sources:
- https://github.com/heptiolabs/eventrouter
version: 0.2.1
